import { afterEach, describe, expect, it, vi } from "vitest";
import { ApprovalQueue } from "./approvalState";
const plugin = { pluginId: "p", version: "1", manifestDigest: "d", harnessApi: 1, minAppVersion: "0.19.0", trusted: true, enabled: true, source: "s", tools: [], capabilities: ["project.read"] };
describe("ApprovalQueue", () => {
  afterEach(() => vi.useRealTimers());
  it("resolves approve or reject once", async () => { const q = new ApprovalQueue(); const answer = q.capability("s", plugin); const id = q.snapshot()[0].id; q.decide(id, true); q.decide(id, false); await expect(answer).resolves.toBe(true); expect(q.snapshot()).toHaveLength(0); });
  it("close and expiry default to reject", async () => { vi.useFakeTimers(); const q = new ApprovalQueue(); const a = q.capability("a", plugin); const b = q.capability("b", plugin); q.rejectSession("a"); vi.advanceTimersByTime(60_001); await expect(a).resolves.toBe(false); await expect(b).resolves.toBe(false); });
  it("keeps sessions isolated", async () => { const q = new ApprovalQueue(); const a = q.capability("a", plugin); const b = q.capability("b", plugin); q.rejectSession("a"); expect(q.snapshot().map((x) => x.sessionId)).toEqual(["b"]); q.rejectAll(); await expect(a).resolves.toBe(false); await expect(b).resolves.toBe(false); });
  it("exposes only command env keys and bounded patch metadata", () => { const q = new ApprovalQueue(); void q.command("p", Date.now() + 1000, { jsonrpc: "2.0", id: "r", method: "tool/request", sessionId: "s", params: { toolId: "t", tool: "command.exec", executable: "echo", argv: ["a b"], env: { LANG: "secret" } } }); const text = JSON.stringify(q.snapshot()[0]); expect(text).toContain("LANG"); expect(text).not.toContain("secret"); q.rejectAll(); });
  it("copies only host preview hunks into patch approval", () => { const q = new ApprovalQueue(); const request = { jsonrpc: "2.0", id: "r", method: "tool/request", sessionId: "s", params: { toolId: "t", tool: "project.patch.propose", relativePath: "a", expectedDigest: "old", replacement: "private replacement" } } as const; void q.patch("p", { previewId: "v", generation: 1, relativePath: "a", originalDigest: "old", replacementDigest: "new", oldLines: 1, newLines: 1, finalBytes: 4, expiresAt: Date.now() + 1000, diff: { hunks: [{ oldStart: 1, newStart: 1, lines: [{ kind: "add", newLine: 1, content: "safe" }] }], truncated: false, omittedHunks: 0, omittedLines: 0, previewBytes: 4 } }, request); const text = JSON.stringify(q.snapshot()[0]); expect(text).toContain("safe"); expect(text).not.toContain("private replacement"); q.rejectAll(); });
});
