import { describe, expect, it, vi } from "vitest";
import { HarnessSessionCoordinator, runnablePlugins } from "./sessionState";
const plugin = { pluginId: "p", version: "1.0.0", manifestDigest: "d", harnessApi: 1, minAppVersion: "0.19.0", trusted: true, enabled: true, source: "fixture", tools: [], capabilities: [] };
describe("Harness session state", () => {
  it("filters candidates by trust compatibility and enabled state", () => expect(runnablePlugins([plugin, { ...plugin, pluginId: "u", trusted: false }, { ...plugin, pluginId: "d", enabled: false }, { ...plugin, pluginId: "n", minAppVersion: "9.0.0" }]).map((x) => x.pluginId)).toEqual(["p"]));
  it("creates no half-live tab on startup or tab failure", async () => { const runtime = { state: "running", start: vi.fn(async () => {}), close: vi.fn(async () => {}) } as any; const c = new HarnessSessionCoordinator(() => runtime); await expect(c.launch({ agentId: "codex", plugin, projectRoot: "/p", createTab: async () => null })).rejects.toThrow(); expect(c.sessions.size).toBe(0); expect(runtime.close).toHaveBeenCalledOnce(); });
  it("isolates two sessions and closes or prunes idempotently", async () => { const made: any[] = []; const c = new HarnessSessionCoordinator(() => { const r = { state: "running", start: vi.fn(async () => {}), close: vi.fn(async () => {}) }; made.push(r); return r as any; }); await c.launch({ agentId: "codex", plugin, projectRoot: "/a", createTab: async () => "a" }); await c.launch({ agentId: "claude", plugin, projectRoot: "/b", createTab: async () => "b" }); await c.retain(new Set(["b"])); await c.close("a"); expect(c.sessions.has("a")).toBe(false); expect(c.sessions.has("b")).toBe(true); expect(made[0].close).toHaveBeenCalledOnce(); });
  it("does not restore or replay sessions in a new coordinator", () => { const c = new HarnessSessionCoordinator(() => ({} as any)); expect(c.sessions.size).toBe(0); });
  it("revokes grants and surfaces reconcile failure", async () => { const runtime = { state: "running", start: vi.fn(async () => {}), close: vi.fn(async () => {}), authorize: vi.fn(async () => { throw new Error("sync"); }) } as any; const c = new HarnessSessionCoordinator(() => runtime); await c.launch({ agentId: "codex", plugin: { ...plugin, capabilities: [] }, projectRoot: "/p", createTab: async () => "a" }); await c.revoke("a"); expect(c.sessions.get("a")?.state.runtime).toBe("reconcile-required"); });
});
